import uuid
import logging
from datetime import datetime, date, time, timezone
from decimal import Decimal
from django.conf import settings
from django import forms
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.contrib import messages
from django.views.generic import ListView
from django.views.generic.detail import SingleObjectMixin
from django.http import HttpResponse, HttpResponseRedirect
from customers.models import Customer
from items.models import Item
from .models import Order, OrderNote, Invoice
from .forms import OrderForm
from .urls import *

logger = logging.getLogger(__name__)

# Create your views here.
def order_create(request, customer_token):
    """
    Function to display the customer_create.html template
    which will allow new customers to be added.
    """
    order_form = OrderForm(request.POST)
    customer = get_object_or_404(Customer, customer_token=customer_token)
    logger.warning("1")
    logger.warning(customer)
    
    if request.method == "POST":
        # Order: customer, item , cost_initial, cost_week,
        # start_date,end_date,created_on,created_by
        # Invoice: order,created_on,amount_paid,note,status
        item = get_object_or_404(Item, id=order_form['item'].value())
        start_date_date = datetime.strptime(order_form['start_date'].value(), '%Y-%m-%d')
        end_date_date = datetime.strptime(order_form['end_date'].value(), '%Y-%m-%d')

        order = Order.objects.create(
            customer = customer,
            item = item,
            cost_initial = Decimal(order_form['cost_initial'].value()),
            cost_week = Decimal(order_form['cost_week'].value()),
            start_date = start_date_date,
            end_date = end_date_date,
            created_by = request.user,
            created_on = datetime.now)
        
        invoice = Invoice.objects.create(
            order = order,
            created_on = datetime.now,
            amount_paid = order_form['cost_initial'].value(),
            note = "First rental payment",
            status = False)
        
        update_item = Item.objects.get(pk=item.id)
        update_item.income += order.cost_initial
        update_item.save()

        logger.warning("18")
        logger.warning(invoice.clean())
        logger.warning(order.clean())
        # Validation occurs in JS, so at this point check if the invoice and order have
        # been created and display success message.
        if invoice.clean() == None and order.clean() == None:
            messages.add_message(
            request, messages.SUCCESS,
            'Order has been saved'
            )#
            return redirect('customers:customer_order_view', customer_token=order.customer.customer_token, id=order.id)
       
    order_form = OrderForm()

    return render(
        request,
        "orders/order_create.html",
        {
            "order_form": order_form,
            "class_var":"Orders",
        },
    )

class OrderList(ListView):
    paginate_by = 9
    model = Order
    # needs to set the class var to Customers if this is 
    #from the customer and not the general order list.
    def get_context_data(self, **kwargs):
        context = super(OrderList, self).get_context_data(**kwargs)
        context['class_var'] = 'Orders'
        return context

def order_view(request, id):
    """
    Function to view a singular order after being selected.
    """
    template_name = "orders/order_view.html"
    
    # Find a singular Item object. Look in "Item" table in the pk
    # primary key field (auto generated by Django).
    obj = get_object_or_404(Item, pk=id)
    # Render the template item_view and send the found "Item" to it.
    return render(
        request,
        "orders/order_view.html",
        {
            "item":obj,
            "class_var":"Items",
        },
    )

class OrderInvoiceList(ListView):
    paginate_by = 5
    model = Invoice
