import uuid
import logging
from datetime import datetime, date, time, timezone
from django.conf import settings
from django import forms
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.contrib import messages
from django.views.generic import ListView
from django.views.generic.detail import SingleObjectMixin
from django.http import HttpResponse, HttpResponseRedirect
from customers.models import Customer
from items.models import Item
from .models import Order, OrderNote, Invoice
from .forms import OrderForm
from .urls import *

logger = logging.getLogger(__name__)

# Create your views here.
def order_create(request, customer_token):
    """
    Function to display the customer_create.html template
    which will allow new customers to be added.
    """
    order_form = OrderForm(request.POST)
    customer = get_object_or_404(Customer, customer_token=customer_token)
    logger.warning("1")
    logger.warning(customer)
    
    if request.method == "POST":
        # Order: customer, item , cost_initial, cost_week,
        # start_date,end_date,created_on,created_by
        item = get_object_or_404(Item, id=order_form['item'].value())
        logger.warning("2")
        logger.warning(item)
        logger.warning("3")
        start_date_date = datetime.strptime(order_form['start_date'].value(), '%Y-%m-%d')
        end_date_date = datetime.strptime(order_form['end_date'].value(), '%Y-%m-%d')
        logger.warning("4")
        logger.warning(start_date_date)
        logger.warning(end_date_date)

        order = Order.objects.create(
            customer = customer,
            item = item,
            cost_initial = order_form['cost_initial'].value(),
            cost_week = order_form['cost_week'].value(),
            start_date = start_date_date,
            end_date = end_date_date,
            created_by = request.user,
            created_on = datetime.now)


        logger.warning("5")
        logger.warning(item)
        logger.warning("6")
        logger.warning(order.cost_initial)
        logger.warning(order_form['cost_initial'].value())
        logger.warning("7")
        logger.warning(order.cost_week)
        logger.warning(order_form['cost_week'].value())
        logger.warning("8")
        logger.warning(order.start_date)
        logger.warning(start_date_date)
        logger.warning("9")
        logger.warning(order.end_date)
        logger.warning(end_date_date)
        logger.warning("10")
        logger.warning(order.created_by)
        logger.warning(request.user)
        logger.warning("11")
        logger.warning(order)
        logger.warning("12")
        logger.warning(request)
        invoice = Invoice()
        invoice.amount_paid = order_form['cost_initial'].value()
        invoice.note = "First Rental Payment"
        invoice.status = False

        logger.warning("13")
        logger.warning(invoice)
        logger.warning("14")
        logger.warning(invoice.amount_paid)
        logger.warning(order_form['cost_initial'].value())
        logger.warning("15")
        logger.warning(invoice.note)
        logger.warning("16")
        logger.warning(invoice.status)

        logger.warning("17")
        logger.warning(order_form.is_valid())

        if order_form.is_valid():
            order.save()
            invoice.save()
            
            messages.add_message(
                request, messages.SUCCESS,
                'Order has been saved'
            )
            
            return redirect('customers:customer_order_view', customer_token=order.customer.customer_token, id=order.id)

    order_form = OrderForm()

    return render(
        request,
        "orders/order_create.html",
        {
            "order_form": order_form,
            "class_var":"Orders",
        },
    )

class OrderList(ListView):
    paginate_by = 9
    model = Order
    # needs to set the class var to Customers if this is 
    #from the customer and not the general order list.
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['class_var'] = 'Orders'
        return context

def order_view(request, id):
    """
    Function to view a singular order after being selected.
    """
    template_name = "orders/order_view.html"
    
    # Find a singular Item object. Look in "Item" table in the pk
    # primary key field (auto generated by Django).
    obj = get_object_or_404(Item, pk=id)
    # Render the template item_view and send the found "Item" to it.
    return render(
        request,
        "orders/order_view.html",
        {
            "item":obj,
            "class_var":"Items",
        },
    )