from django.shortcuts import render
from django.http import HttpResponse

from django.shortcuts import render, get_object_or_404, reverse
from django.contrib import messages
from django.views.generic import ListView
from django.http import HttpResponseRedirect
from .models import Customer, CustomerNote

# Create your views here.
class CustomerList(ListView):
    paginate_by = 9
    model = Customer

def customer_view(request, customer_token):
    """
    Function to view a singular item after being selected.
    """
    template_name = "items/item_view.html"
    
    # Find a singular Item object. Look in "Item" table in the pk
    # primary key field (auto generated by Django).
    obj = get_object_or_404(Item, pk=id)
    # Render the template item view and send the found "Item" to it.
    return render(
        request,
        "items/item_view.html",
        {
            "item":obj,
        },
    )


#def customer_search(request):
#    """
#    Function to load the customer search feature
#    """
#    
#    
#    return HttpResponse('Hello Customer Search!')