# Generated by Django 4.2.13 on 2024-05-12 02:33

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cost_initial', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cost_week', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('collect_date', models.DateField(blank=True, null=True)),
                ('repair_date', models.DateField(blank=True, null=True)),
                ('income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_type', to='items.itemtype')),
            ],
        ),
    ]
