# Generated by Django 4.2.13 on 2024-05-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_serial',
            field=models.CharField(default='00001', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemtype',
            name='category',
            field=models.CharField(default='Category', max_length=200),
            preserve_default=False,
        ),
    ]
