# Generated by Django 4.2.13 on 2024-05-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_item_serial_itemtype_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_serial',
            field=models.CharField(default='SerialNumber', max_length=200),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='category',
            field=models.CharField(default='Category', max_length=200),
        ),
    ]
