# Generated by Django 4.2.13 on 2024-05-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_itemtype_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['item_type']},
        ),
        migrations.AlterModelOptions(
            name='itemtype',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(0, 'Available'), (1, 'Scrapped'), (2, 'Lost/Stolen')], default=0),
        ),
    ]
