# Generated by Django 4.2.13 on 2024-05-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_options_alter_itemtype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_serial',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(0, 'Available'), (1, 'Scrapped'), (2, 'Lost/Stolen'), (3, 'Sold')], default=0),
        ),
    ]
