# Generated by Django 4.2.13 on 2024-06-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(0, 'Available'), (1, 'Scrapped'), (2, 'Missing'), (3, 'Sold'), (4, 'Repair')], default=0),
        ),
    ]
