# Generated by Django 4.2.13 on 2024-05-12 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customernote_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_id',
            new_name='customer_token',
        ),
    ]
