# Generated by Django 4.2.13 on 2024-06-13 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_alter_customernote_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customernote',
            options={'ordering': ['created_on', 'id']},
        ),
    ]
