# Generated by Django 4.2.13 on 2024-05-13 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
