# Generated by Django 4.2.13 on 2024-06-07 00:19

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_order_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='ordernote',
            options={'ordering': ['created_by']},
        ),
        migrations.AlterField(
            model_name='ordernote',
            name='note',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
